resolver: nightly-2018-01-21

nix:
  # enable: true
  pure:   false
  packages:
  - zlib
  - freealut
  - freeglut

packages:
- ./

- location:
    git:    https://github.com/sboosali/spiros
    commit: dbe489d428ec0c6f1700fde703cbdd90738b0f14
  extra-dep: true
  subdirs: [.]
